# permissions for end users to edit k8scontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: k8scontroller-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-controller
    app.kubernetes.io/part-of: k8s-controller
    app.kubernetes.io/managed-by: kustomize
  name: k8scontroller-editor-role
rules:
- apiGroups:
  - api.lazyboson.ai
  resources:
  - k8scontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.lazyboson.ai
  resources:
  - k8scontrollers/status
  verbs:
  - get
