---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.lazyboson.ai
  resources:
  - k8scontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.lazyboson.ai
  resources:
  - k8scontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - api.lazyboson.ai
  resources:
  - k8scontrollers/status
  verbs:
  - get
  - patch
  - update
